version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - 7700
    networks:
      - search_engine

  ad_versionem:
    build: .
    ports:
      - 8080:8080
    networks:
      - search_engine
    environment:
      - MEILISEARCH_HOST="http://meilisearch:7700"

networks:
  search_engine:
