openapi: 3.0.0

info:
  title: Note versionner API
  description: API for the Notes versionner application
  version: 0.0.0

basePath: /api

paths:
  /docs:
    get:
      description: Swagger UI of the API
      responses:
        200:
          description: HTML page to render Swagger UI.
