openapi: 3.0.0

info:
  title: Note versionner API
  description: API for the Notes versionner application
  version: 0.0.0

servers:
  - url: /api
    description: Current environment

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    Unauthorized:
      description: Access to route can only be granted through authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessDeniedResource'

    Forbidden:
      description: Access is blocked because current user doesn't have the required privileges to access it
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccessDeniedResource'

    SuccessfullLogin:
      description: Login success
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginSuccessData'

  schemas:
    UserRegistrationData:
      description: Data required to create a user account
      type: object
      properties:
        username:
          description: Unique identifier of the user, will serve as a login credential
          type: string
          pattern: '^[a-zA-Z0-9-_]$'
          example: 'H4ckerman'
        password:
          description: Password for the user, will serve as the second half of the login credentials
          type: string
          example: 'Sup3rStrongP4SsW0rd'
        email:
          description: Email adress of the user
          type: string
          example: 'john.doe@mail.com'
      required:
        - username
        - password
        - email

    LoginSuccessData:
      description: Login success data with an authentication token
      type: object
      properties:
        username:
          description: Username of the logged-in user
          type: string
          example: 'H4ckerman'
        token:
          description: JWT Token to be used in the Authorization header with Bearer authentication type
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    LoginFormData:
      description: Login information
      type: object
      properties:
        username:
          description: Username of the user to log in
          type: string
          pattern: '^[a-zA-Z0-9-_]$'
          example: 'H4ckerman'
        password:
          description: Password of the user to log in
          type: string
      required:
        - username
        - password

    AccessDeniedResource:
      type: object
      properties:
        resource:
          description: The resource access was attempted to
          type: string

    UserData:
      type: object
      properties:
        username:
          type: string
          description: Username of the user
          example: 'H4ckerman'
        email:
          type: string
          description: Email of the user
          example: 'john.doe@mail.com'
        uid:
          type: string
          description: Unique identifier of the user
          example: 'PPBqWA9'

paths:
  ################################################################
  # Documentation routes
  ################################################################

  /docs:
    get:
      description: Swagger UI of the API
      tags:
        - Documentation
      responses:
        200:
          description: HTML page to render Swagger UI.

  ################################################################
  # Auth routes
  ################################################################

  /auth/register:
    post:
      description: Create a new user account
      tags:
        - Auth
      requestBody:
        description: Registration data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistrationData'
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationData'
      responses:
        201:
          description: Account created
          $ref: '#/components/responses/SuccessfullLogin'
        409:
          description: Username or email already in use by another user
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    description: The reason why the account creation is declined
                    type: string
                    enum:
                      - 'Username already used by another user'
                      - 'Email already used by another user'

  /auth/login:
    post:
      description: Login to an existing account
      tags:
        - Auth
      requestBody:
        description: Login information
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginFormData'
          application/json:
            schema:
              $ref: '#/components/schemas/LoginFormData'
      responses:
        200:
          $ref: '#/components/responses/SuccessfullLogin'
        401:
          description: Wrong credentials combination
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
                    enum:
                      - 'Wrong credentials'
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    description: Username which no user can be found with
                    type: string
                    example: 'AgentSmith'
                  reason:
                    type: string
                    enum:
                      - 'User not found'

  ################################################################
  # Users routes
  ################################################################

  /users/{username}:
    get:
      description: Get the data associated to a user
      tags:
        - Users
      parameters:
        - name: username
          in: path
          required: true
          description: User to read data of
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: User data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
